### ISSUE TITLE
Major dupe glitch (Hopper into storage controller)

### ISSUE THREAD

**Issue by BirbRoss** [Salandora/SophisticatedStorage#6] opened 2024-05-19 13:28 UTC
**Describe the bug**
By placing a hopper facing a storage controller then puttting any item in it and connecting any barrel to the controller will dupe items from the hopper until the barrel is full, at which point it will finally consume the item in the hopper

**To Reproduce**
1. Open world
2. Place Storage controller, Hopper & Any storage device
3.  Put item you want to dupe in hopper
4.  Will dupe item until storage is full

**Also can't right click to deposite items into storage controller.**

**Expected behavior**
It only puts 1 item into the drawer

**Screenshots**
https://youtu.be/VoR0mT8j3ZE

**Versions**
fabric-api-0.92.1+1.20.1.jar
ModernKeyBinding-Fabric-1.20-1.2.0.jar
sophisticatedbackpacks-3.19.4+mc1.20.1-SNAPSHOT-build.39.jar
ophisticatedcore-0.5.108+mc1.20.1-SNAPSHOT-build.39.jar
sophisticatedstorage-0.8.59+mc1.20.1-SNAPSHOT-build.39.jar

Minecraft 1.20.1
Fabric 0.15.11

**Comment by Salandora** [comment] 2024-05-19 21:36
Duplicate of #2 and #5.
Fixed in dev, will be release soon

**Closed as completed by Salandora** 2024-05-19 21:36 UTC
